/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GC;

import java.awt.event.KeyEvent;
import java.util.List;
import java.util.ArrayList;
//import java.util.Iterator;
import javax.swing.JTextField;

/**
 *
 * @author Ian
 */
public class ScaleInfo extends javax.swing.JFrame {

   private List<Integer> si;
   private List<JTextField> tf;
   private  boolean not_valid;
    /**
     * Creates new form ScaleInfo
     */
    public ScaleInfo() {
        si = new ArrayList<Integer>();
        tf = new ArrayList<JTextField>();
        not_valid = false;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        aTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Final Exam Grade Needed");

        jLabel1.setText("Enter The lowest grade possible for each letter grade!");

        jLabel2.setText("A");

        aTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aTextFieldActionPerformed(evt);
            }
        });
        aTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                aTextFieldKeyPressed(evt);
            }
        });

        jLabel3.setText("B");

        bTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bTextFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bTextFieldKeyTyped(evt);
            }
        });

        jLabel4.setText("C");

        cTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cTextFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cTextFieldKeyTyped(evt);
            }
        });

        jLabel5.setText("D");

        dTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dTextFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dTextFieldKeyTyped(evt);
            }
        });

        jButton1.setText("Enter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(aTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 240, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bTextField))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cTextField))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(aTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aTextFieldActionPerformed
        // TODO add your handling code here:
 
        
    }//GEN-LAST:event_aTextFieldActionPerformed

  private void addTextFields(){
       tf.add(aTextField);
       tf.add(bTextField);
       tf.add(cTextField);
       tf.add(dTextField);
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //tf.clear();
        not_valid = false;
        addTextFields();
        
        String s = tf.get(0).getText();
        if(s.equals("")){
            s = "-1";
            not_valid = true;
        }
        Integer t = new Integer(s);
        Integer t2 = new Integer("100");
        
        if(t >= t2 || t <= 0)
        {
            not_valid = true;
            tf.get(0).setText("");
        }
        
        si.add(t);
        
        for(int i = 1; i < 4; i++){
            String t1 = tf.get(i).getText();
            if(t1.equals("")){
                t1 = "-1";
                not_valid = true;
            }
            t = Integer.parseInt(t1);
            if(t >= si.get(i-1)|| t <= 0)
            {
                not_valid = true;
                tf.get(i).setText("");
            }
            
            
            si.add(t);    
        }
        tf.clear();
        if(not_valid){
            new Error().setVisible(true);
            si.clear();
        }
        else{
            this.dispose();
            new GradeCats(si).setVisible(true);
        }
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void aTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aTextFieldKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_DOWN){
            bTextField.requestFocusInWindow();
        }
    }//GEN-LAST:event_aTextFieldKeyPressed

    private void bTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bTextFieldKeyTyped
        // TODO add your handling code here:
 
    }//GEN-LAST:event_bTextFieldKeyTyped

    private void cTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cTextFieldKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_cTextFieldKeyTyped

    private void dTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dTextFieldKeyTyped
        // TODO add your handling code here:

 
    }//GEN-LAST:event_dTextFieldKeyTyped

    private void bTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bTextFieldKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_DOWN){
            cTextField.requestFocusInWindow();
        }
        if (evt.getKeyCode() == KeyEvent.VK_UP){
            aTextField.requestFocusInWindow();
        }
    }//GEN-LAST:event_bTextFieldKeyPressed

    private void cTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cTextFieldKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_DOWN){
            dTextField.requestFocusInWindow();
        }
        if (evt.getKeyCode() == KeyEvent.VK_UP){
            bTextField.requestFocusInWindow();
        }                
    }//GEN-LAST:event_cTextFieldKeyPressed

    private void dTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dTextFieldKeyPressed
        // TODO add your handling code here:
       if (evt.getKeyCode() == KeyEvent.VK_UP){
            cTextField.requestFocusInWindow();
        }                
    }//GEN-LAST:event_dTextFieldKeyPressed

    
   
    
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScaleInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScaleInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScaleInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScaleInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScaleInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aTextField;
    private javax.swing.JTextField bTextField;
    private javax.swing.JTextField cTextField;
    private javax.swing.JTextField dTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    // End of variables declaration//GEN-END:variables
   
}
